<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<html lang="cs"
      data-layout="semibox"
      data-layout-style="default"
      data-sidebar="dark"
      data-topbar="dark"
      data-sidebar-size="lg"
      data-sidebar-image="img-2"
      data-preloader="enable"
      data-sidebar-visibility="show"
      data-layout-mode="light"
      data-layout-width="fluid"
      data-layout-position="fixed">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex">
        <title>Server Error</title>
        <!-- Layout config Js -->
        <script src="/assets/js/layout.js"></script>
        <!-- Bootstrap Css -->
        <link href="/assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="/assets/css/custom.min.css" id="app-style" rel="stylesheet" type="text/css" />
    </head>

    <body>
    <div class="auth-page-wrapper py-5 d-flex justify-content-center align-items-center min-vh-100">

        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden p-0">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-xl-4 text-center">
                        <div class="error-500 position-relative">
                            <img src="/assets/images/error500.png" alt="" class="img-fluid error-500-img error-img" />
                            <h1 class="title text-muted">500</h1>
                        </div>
                        <div>
                            <h4>Interní chyba!</h4>
                            <p class="text-muted w-75 mx-auto">Hups, něco se pokazilo</p>
                            <p class="text-muted w-75 mx-auto">Předali jsme to na vývoj, kde se pracuje na nápravě.</p>
                            <p class="text-muted w-75 mx-auto">Zkuste to, prosím, později.</p>
                            <a href="/" class="btn btn-info"><i class="mdi mdi-home me-1"></i>Zpět na úvodní stránku</a>
                        </div>
                    </div><!-- end col-->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth-page content -->
    </div>
    </body>

    <script>
        document.body.insertBefore(document.getElementById('nette-error'), document.body.firstChild);
    </script>
</html>